/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./src/components/utils/menu/AdminMenu.vue')['default']
    BaseEchart: typeof import('./src/components/charts/BaseEchart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    Error: typeof import('./src/components/Error.vue')['default']
    FeedbackManage: typeof import('./src/components/admin/FeedbackManage.vue')['default']
    HeaderBanner: typeof import('./src/components/utils/HeaderBanner.vue')['default']
    HeaderUserStatus: typeof import('./src/components/utils/HeaderUserStatus.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    PieEchart: typeof import('./src/components/charts/PieEchart.vue')['default']
    Recommendation: typeof import('./src/components/user/Recommendation.vue')['default']
    RecommendationCard: typeof import('./src/components/utils/RecommendationCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentMenu: typeof import('./src/components/utils/menu/StudentMenu.vue')['default']
    UniversityInfoQuery: typeof import('./src/components/user/UniversityInfoQuery.vue')['default']
    UniversityListCard: typeof import('./src/components/utils/UniversityListCard.vue')['default']
    UniversityManage: typeof import('./src/components/admin/UniversityManage.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserManage: typeof import('./src/components/admin/UserManage.vue')['default']
  }
}
